import { Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from './components/shared/Navbar'
import Footer from './components/shared/Footer'
import TopBar from './components/home/TopBar'
import MegaMenu from './components/shared/MegaMenu'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <TopBar />
      <MegaMenu />

        {children}
      <Footer />
        </body>
    </html>
  )
}
